export const CULTES = [
    'anabaptiste',
    'anubien',
    'apocalyptique',
    'blafard',
    'chroniqueur',
    'claniste',
    'ferrailleur',
    'fleau',
    'hellvetique',
    'jehammetan',
    'juge',
    'neolybien',
    'spitalier'
];

export const CULTURES = [
    'afrika',
    'balkhan',
    'borca',
    'franka',
    'hybrispanie',
    'pollen',
    'purgare'
];

export const CONCEPTS = [
    'abomination',
    'aventurier',
    'chef',
    'chercheur',
    'conquerant',
    'createur',
    'destructeur',
    'disciple',
    'elu',
    'ermite',
    'fanatique',
    'heretique',
    'martyr',
    'mediateur',
    'mentor',
    'profanateur',
    'protecteur',
    'soigneur',
    'traditionnaliste',
    'vertueux',
    'visionnaire',
    'voyageur'
];

export const ATTRIBUTES = [
    'physique',
    'agilite',
    'charisme',
    'intellect',
    'psyche',
    'instinct',
];

export const SKILLS = [

];

export const POTENTIALS = [
    'test'
];

export const SEX = [
    'male',
    'female',
    'hermaphrodite'
];

export const RANGS = [
    [
        'ravi',
        'ascete',
        'elyseen',
        'orgiastique',
        'fureur',
        'emissaire',
        'conseiller',
        'baptiste',
        'sublime',
        'archeron'
    ],
    [
        'initie',
        'enchanteur',
        'embaumeur',
        'prophetedesames',
        'guerisseur',
        'hecateen',
        'faucille',
        'ammout',
        'hogon'
    ],
    [
        'pinson',
        'epervier',
        'pie',
        'vautour',
        'coucou',
        'chouette',
        'picvert',
        'cigogne',
        'corneille',
        'sterne',
        'mouette',
        'pelican',
        'albatros',
        'colibri',
        'marabout',
        'ibis',
        'toko',
        'busard',
        'phenix'
    ],
    [
        'spectre',
        'solaire',
        'aurore',
        'eveilleur',
        'redempteur',
        'fantome',
        'cyclope',
        'aspirant',
        'demagogue',
        'halo'
    ],
    [
        'bit',
        'agent',
        'mediateur',
        'diffuseur',
        'fragment',
        'paradigme',
        'occulteur',
        'fusible',
        'skalar',
        'zero',
        'aiguille'
    ],
    [
        'eclaireur',
        'chasseur',
        'cueilleur',
        'guerriertribal',
        'chaman',
        'chefdeclan',
        'champion',
        'fondateur'
    ],
    [
        'souris',
        'blaireau',
        'renard',
        'loupsolitaire',
        'oursdescavernes',
        'mecanicien',
        'artisan',
        'recuperateur',
        'loupalpha',
        'legende',
        'malfrat',
        'estimateur',
        'officier'
    ],
    [
        'dufu',
        'hondo',
        'chaga',
        'damu',
        'simba',
        'dumisai',
        'moyo',
        'kifo'
    ],
    [
        'soldat',
        'caporal',
        'sapeur',
        'grenadier',
        'forcespecial',
        'garde',
        'transmetteur',
        'eclaireur',
        'infiltre',
        'escouade',
        'medecin',
        'ingenieur',
        'approvisionneur',
        'subalterne',
        'officiersup',
        'commandant'
    ],
    [
        'ismaeli',
        'glaive',
        'abrami',
        'berger',
        'isaaki',
        'bienfait',
        'iconide',
        'prophete',
        'hagari',
        'dalila',
        'voix',
        'juste',
        'saraeli',
        'fierte',
        'maculee',
        'immaculee',
        'oracle',
        'arianoi',
        'sangdaries',
        'fatum'
    ],
    [
        'vagabond',
        'jugedeville',
        'protecteur',
        'executeur',
        'jugenoir',
        'avocat',
        'arbitre',
        'contrôleur',
        'commissaire',
        'procureur',
        'senateur',
        'jugesupreme'
    ],
    [
        'apprenti',
        'scribe',
        'marchand',
        'navigateur',
        'cartographe',
        'grandchasseur',
        'magnat',
        'cheik',
        'pillard',
        'ambassadeur',
        'waziri',
        'consul'
    ],
    [
        'recrue',
        'aidesoignant',
        'fambulancier',
        'medecinterrain',
        'hygieniste',
        'chirurgien',
        'epigeneticien',
        'pharmacien',
        'hippocrate',
        'anesthesiste',
        'chef',
        'specialiste',
        'preserviste',
        'commando',
        'recteur',
        'medecinvillage',
        'ancien'
    ]
]